// import type { MusicAlbum } from "@/store/audioStore";

import type { MusicAlbum } from "@/type/music";

// const Listdata = [
//   "105-你是否梦想到那地",
//   "109-你的信实广大",
//   "111-hallelujah",
//   "112-你真伟大",
//   "114 hallelujah赞美耶和华",
//   "116-你的名何等威严",
//   "117-我已经决定",
//   "118 我确知我救主活着",
//   "119我要求告耶和华",
//   "120 我会庆祝",
//   "122-我不以神的名为耻",
//   "123-神的国度-English",
//   "123-神的国度-中文",
//   "127-他名称为奇妙,",
//   "131-奋起上主子民",
//   "132-Lord God, Almighty",
//   "133-看何等荣耀景象",
//   "134-唱Hal-le-lu-jah",
//   "136- Walking On Heaven's Road",
//   "137-生命之泉",
//   "138-感谢神",
//   "139-奇妙神",
//   "141-哪有朋友像耶稣",
//   "142-同往迦南地",
//   "145-同往锡安",
//   "146-都到天国",
//   "147-世界的光",
//   "148-倚靠耶稣永远膀臂",
//   "150-耶和华我的心仰望你",
//   "151-赐生命的主",
//   "154-阿拉法俄梅戛",
//   "155-常常喜乐,",
//   "170-万王之王",
//   "174-All in all",
//   "179-带领我今日得人,",
//   "182-诗篇63",
//   "183-Let your living water flow",
//   "191-主，我高举你的名",
//   "195-神的羔羊",
//   "198-耶稣是主",
//   "203-欢呼主耶稣",
//   "206-耶和华所定的日子",
//   "211-教导我耐心等",
//   "212-向高处行",
//   "215-信靠顺服",
//   "215-信靠顺服-English",
//   "219-仰望那山",
//   "221-我罪极重",
//   "225-有一位神",
//   "233-喜传福音",
//   "237-耶稣恩友",
//   "253-万福源头",
//   "259-我以祷告来到你跟前",
//   "265-欢声唱",
//   "269-我要向高山举目",
//   "271-美哉主耶稣",
//   "275-爱救了我",
//   "278-为我异象,",
//   "279-靠近十架,",
//   "280-求主同住,",
//   "284-主耶和华是我牧者",
//   "285-使我做你和平差使",
//   "286 Victory in Jesus",
//   "288-充满我",
//   "289-古旧十架",
//   "291-Anchor for the Soul",
//   "292 Lead me to the Rock",
//   "293-有人在为你祷告",
//   "主看顾小羊",
//   "Joy to the world",
//   "O Come, All Ye Faithfull",
//   "Silent Night",
//   "Hark! The Herald Angles Sing"
// ];

// export const ihopeAlbum:MusicAlbum = {
//     id: "ihope",
//     pic:['https://bible-1328751369.cos.ap-guangzhou.myqcloud.com/pic/star-4399.jpg'],
//     authorName:'IHOPE',
//     albumTitle:'Ihope',
//     musics: [{
//         id: "ihope-289",//前缀:ihope-  , 如果有数字则写入数字,如果重复则再后面使用一个随机字母,注意,id唯一不能重复
//         link: "https://bible-1328751369.cos.ap-guangzhou.myqcloud.com/music/289-古旧十架.mp3",//前缀:'https://bible-1328751369.cos.ap-guangzhou.myqcloud.com/music/',后缀:'.mp3'
//         songTitle:'289-古旧十架',// 英文名称则这里置空   ,如果有数字都需要带数字
//         songEnglishTitle:'',//如果是英文名称填入这里, 如果有数字都需要带数字
//         album:'ihope',//不变
//         artistName:'IHOPE',//不变
//     },...]
// }

// // https://bible-1328751369.cos.ap-guangzhou.myqcloud.com/music/289-古旧十架.mp3



export const ihopeAlbum: MusicAlbum = {
  id: "ihope",
  pic: [
    "https://bible-1328751369.cos.ap-guangzhou.myqcloud.com/pic/star-4399.jpg",
  ],
  authorName: "IHOPE",
  albumTitle: "Ihope",
  musics: [
    {
      id: "ihope-105",
      link: "https://bible-1328751369.cos.ap-guangzhou.myqcloud.com/music/105-你是否梦想到那地.mp3",
      songTitle: "105-你是否梦想到那地",
      songEnglishTitle: "",
      album: "ihope",
      artistName: "IHOPE",
    },
    {
      id: "ihope-109",
      link: "https://bible-1328751369.cos.ap-guangzhou.myqcloud.com/music/109-你的信实广大.mp3",
      songTitle: "109-你的信实广大",
      songEnglishTitle: "",
      album: "ihope",
      artistName: "IHOPE",
    },
    {
      id: "ihope-111",
      link: "https://bible-1328751369.cos.ap-guangzhou.myqcloud.com/music/111-hallelujah.mp3",
      songTitle: "",
      songEnglishTitle: "111-hallelujah",
      album: "ihope",
      artistName: "IHOPE",
    },
    {
      id: "ihope-112",
      link: "https://bible-1328751369.cos.ap-guangzhou.myqcloud.com/music/112-你真伟大.mp3",
      songTitle: "112-你真伟大",
      songEnglishTitle: "",
      album: "ihope",
      artistName: "IHOPE",
    },
    {
      id: "ihope-114",
      link: "https://bible-1328751369.cos.ap-guangzhou.myqcloud.com/music/114 hallelujah赞美耶和华.mp3",
      songTitle: "114-hallelujah赞美耶和华",
      songEnglishTitle: "",
      album: "ihope",
      artistName: "IHOPE",
    },
    {
      id: "ihope-116",
      link: "https://bible-1328751369.cos.ap-guangzhou.myqcloud.com/music/116-你的名何等威严.mp3",
      songTitle: "116-你的名何等威严",
      songEnglishTitle: "",
      album: "ihope",
      artistName: "IHOPE",
    },
    {
      id: "ihope-117",
      link: "https://bible-1328751369.cos.ap-guangzhou.myqcloud.com/music/117-我已经决定.mp3",
      songTitle: "117-我已经决定",
      songEnglishTitle: "",
      album: "ihope",
      artistName: "IHOPE",
    },
    {
      id: "ihope-118",
      link: "https://bible-1328751369.cos.ap-guangzhou.myqcloud.com/music/118 我确知我救主活着.mp3",
      songTitle: "118-我确知我救主活着",
      songEnglishTitle: "",
      album: "ihope",
      artistName: "IHOPE",
    },
    {
      id: "ihope-119",
      link: "https://bible-1328751369.cos.ap-guangzhou.myqcloud.com/music/119 我要求告耶和华.mp3",
      songTitle: "119-我要求告耶和华",
      songEnglishTitle: "",
      album: "ihope",
      artistName: "IHOPE",
    },
    {
      id: "ihope-120",
      link: "https://bible-1328751369.cos.ap-guangzhou.myqcloud.com/music/120 我会庆祝.mp3",
      songTitle: "120-我会庆祝",
      songEnglishTitle: "",
      album: "ihope",
      artistName: "IHOPE",
    },
    {
      id: "ihope-122",
      link: "https://bible-1328751369.cos.ap-guangzhou.myqcloud.com/music/122-我不以神的名为耻.mp3",
      songTitle: "122-我不以神的名为耻",
      songEnglishTitle: "",
      album: "ihope",
      artistName: "IHOPE",
    },
    {
      id: "ihope-123e",
      link: "https://bible-1328751369.cos.ap-guangzhou.myqcloud.com/music/123-神的国度-English.mp3",
      songTitle: "",
      songEnglishTitle: "123-神的国度-English",
      album: "ihope",
      artistName: "IHOPE",
    },
    {
      id: "ihope-123c",
      link: "https://bible-1328751369.cos.ap-guangzhou.myqcloud.com/music/123-神的国度-中文.mp3",
      songTitle: "123-神的国度-中文",
      songEnglishTitle: "",
      album: "ihope",
      artistName: "IHOPE",
    },
    {
      id: "ihope-127",
      link: "https://bible-1328751369.cos.ap-guangzhou.myqcloud.com/music/127-他名称为奇妙.mp3",
      songTitle: "127-他名称为奇妙",
      songEnglishTitle: "",
      album: "ihope",
      artistName: "IHOPE",
    },
    {
      id: "ihope-131",
      link: "https://bible-1328751369.cos.ap-guangzhou.myqcloud.com/music/131-奋起上主子民.mp3",
      songTitle: "131-奋起上主子民",
      songEnglishTitle: "",
      album: "ihope",
      artistName: "IHOPE",
    },
    {
      id: "ihope-132",
      link: "https://bible-1328751369.cos.ap-guangzhou.myqcloud.com/music/132-Lord God, Almighty.mp3",
      songTitle: "",
      songEnglishTitle: "132-Lord God, Almighty",
      album: "ihope",
      artistName: "IHOPE",
    },
    {
      id: "ihope-133",
      link: "https://bible-1328751369.cos.ap-guangzhou.myqcloud.com/music/133-看何等荣耀景象.mp3",
      songTitle: "133-看何等荣耀景象",
      songEnglishTitle: "",
      album: "ihope",
      artistName: "IHOPE",
    },
    {
      id: "ihope-134",
      link: "https://bible-1328751369.cos.ap-guangzhou.myqcloud.com/music/134-唱Hal-le-lu-jah.mp3",
      songTitle: "134-唱Hal-le-lu-jah",
      songEnglishTitle: "",
      album: "ihope",
      artistName: "IHOPE",
    },
    {
      id: "ihope-136",
      link: "https://bible-1328751369.cos.ap-guangzhou.myqcloud.com/music/136- Walking On Heaven's Road.mp3",
      songTitle: "",
      songEnglishTitle: "136-Walking On Heaven's Road",
      album: "ihope",
      artistName: "IHOPE",
    },
    {
      id: "ihope-137",
      link: "https://bible-1328751369.cos.ap-guangzhou.myqcloud.com/music/137-生命之泉.mp3",
      songTitle: "137-生命之泉",
      songEnglishTitle: "",
      album: "ihope",
      artistName: "IHOPE",
    },
    {
      id: "ihope-138",
      link: "https://bible-1328751369.cos.ap-guangzhou.myqcloud.com/music/138-感谢神.mp3",
      songTitle: "138-感谢神",
      songEnglishTitle: "",
      album: "ihope",
      artistName: "IHOPE",
    },
    {
      id: "ihope-139",
      link: "https://bible-1328751369.cos.ap-guangzhou.myqcloud.com/music/139-奇妙神.mp3",
      songTitle: "139-奇妙神",
      songEnglishTitle: "",
      album: "ihope",
      artistName: "IHOPE",
    },
    {
      id: "ihope-141",
      link: "https://bible-1328751369.cos.ap-guangzhou.myqcloud.com/music/141-哪有朋友像耶稣.mp3",
      songTitle: "141-哪有朋友像耶稣",
      songEnglishTitle: "",
      album: "ihope",
      artistName: "IHOPE",
    },
    {
      id: "ihope-142",
      link: "https://bible-1328751369.cos.ap-guangzhou.myqcloud.com/music/142-同往迦南地.mp3",
      songTitle: "142-同往迦南地",
      songEnglishTitle: "",
      album: "ihope",
      artistName: "IHOPE",
    },
    {
      id: "ihope-145",
      link: "https://bible-1328751369.cos.ap-guangzhou.myqcloud.com/music/145-同往锡安.mp3",
      songTitle: "145-同往锡安",
      songEnglishTitle: "",
      album: "ihope",
      artistName: "IHOPE",
    },
    {
      id: "ihope-146",
      link: "https://bible-1328751369.cos.ap-guangzhou.myqcloud.com/music/146-都到天国.mp3",
      songTitle: "146-都到天国",
      songEnglishTitle: "",
      album: "ihope",
      artistName: "IHOPE",
    },
    {
      id: "ihope-147",
      link: "https://bible-1328751369.cos.ap-guangzhou.myqcloud.com/music/147-世界的光.mp3",
      songTitle: "147-世界的光",
      songEnglishTitle: "",
      album: "ihope",
      artistName: "IHOPE",
    },
    {
      id: "ihope-148",
      link: "https://bible-1328751369.cos.ap-guangzhou.myqcloud.com/music/148-倚靠耶稣永远膀臂.mp3",
      songTitle: "148-倚靠耶稣永远膀臂",
      songEnglishTitle: "",
      album: "ihope",
      artistName: "IHOPE",
    },
    {
      id: "ihope-150",
      link: "https://bible-1328751369.cos.ap-guangzhou.myqcloud.com/music/150-耶和华我的心仰望你.mp3",
      songTitle: "150-耶和华我的心仰望你",
      songEnglishTitle: "",
      album: "ihope",
      artistName: "IHOPE",
    },
    {
      id: "ihope-151",
      link: "https://bible-1328751369.cos.ap-guangzhou.myqcloud.com/music/151-赐生命的主.mp3",
      songTitle: "151-赐生命的主",
      songEnglishTitle: "",
      album: "ihope",
      artistName: "IHOPE",
    },
    {
      id: "ihope-154",
      link: "https://bible-1328751369.cos.ap-guangzhou.myqcloud.com/music/154-阿拉法俄梅戛.mp3",
      songTitle: "154-阿拉法俄梅戛",
      songEnglishTitle: "",
      album: "ihope",
      artistName: "IHOPE",
    },
    {
      id: "ihope-155",
      link: "https://bible-1328751369.cos.ap-guangzhou.myqcloud.com/music/155-常常喜乐.mp3",
      songTitle: "155-常常喜乐",
      songEnglishTitle: "",
      album: "ihope",
      artistName: "IHOPE",
    },
    {
      id: "ihope-170",
      link: "https://bible-1328751369.cos.ap-guangzhou.myqcloud.com/music/170-万王之王.mp3",
      songTitle: "170-万王之王",
      songEnglishTitle: "",
      album: "ihope",
      artistName: "IHOPE",
    },
    {
      id: "ihope-174",
      link: "https://bible-1328751369.cos.ap-guangzhou.myqcloud.com/music/174-All in all.mp3",
      songTitle: "",
      songEnglishTitle: "174-All in all",
      album: "ihope",
      artistName: "IHOPE",
    },
    {
      id: "ihope-179",
      link: "https://bible-1328751369.cos.ap-guangzhou.myqcloud.com/music/179-带领我今日得人.mp3",
      songTitle: "179-带领我今日得人",
      songEnglishTitle: "",
      album: "ihope",
      artistName: "IHOPE",
    },
    {
      id: "ihope-182",
      link: "https://bible-1328751369.cos.ap-guangzhou.myqcloud.com/music/182-诗篇63.mp3",
      songTitle: "182-诗篇63",
      songEnglishTitle: "",
      album: "ihope",
      artistName: "IHOPE",
    },
    {
      id: "ihope-183",
      link: "https://bible-1328751369.cos.ap-guangzhou.myqcloud.com/music/183-Let your living water flow.mp3",
      songTitle: "",
      songEnglishTitle: "183-Let your living water flow",
      album: "ihope",
      artistName: "IHOPE",
    },
    {
      id: "ihope-191",
      link: "https://bible-1328751369.cos.ap-guangzhou.myqcloud.com/music/191-主，我高举你的名.mp3",
      songTitle: "191-主，我高举你的名",
      songEnglishTitle: "",
      album: "ihope",
      artistName: "IHOPE",
    },
    {
      id: "ihope-195",
      link: "https://bible-1328751369.cos.ap-guangzhou.myqcloud.com/music/195-神的羔羊.mp3",
      songTitle: "195-神的羔羊",
      songEnglishTitle: "",
      album: "ihope",
      artistName: "IHOPE",
    },
    {
      id: "ihope-198",
      link: "https://bible-1328751369.cos.ap-guangzhou.myqcloud.com/music/198-耶稣是主.mp3",
      songTitle: "198-耶稣是主",
      songEnglishTitle: "",
      album: "ihope",
      artistName: "IHOPE",
    },
    {
      id: "ihope-203",
      link: "https://bible-1328751369.cos.ap-guangzhou.myqcloud.com/music/203-欢呼主耶稣.mp3",
      songTitle: "203-欢呼主耶稣",
      songEnglishTitle: "",
      album: "ihope",
      artistName: "IHOPE",
    },
    {
      id: "ihope-206",
      link: "https://bible-1328751369.cos.ap-guangzhou.myqcloud.com/music/206-耶和华所定的日子.mp3",
      songTitle: "206-耶和华所定的日子",
      songEnglishTitle: "",
      album: "ihope",
      artistName: "IHOPE",
    },
    {
      id: "ihope-211",
      link: "https://bible-1328751369.cos.ap-guangzhou.myqcloud.com/music/211-教导我耐心等.mp3",
      songTitle: "211-教导我耐心等",
      songEnglishTitle: "",
      album: "ihope",
      artistName: "IHOPE",
    },
    {
      id: "ihope-212",
      link: "https://bible-1328751369.cos.ap-guangzhou.myqcloud.com/music/212-向高处行.mp3",
      songTitle: "212-向高处行",
      songEnglishTitle: "",
      album: "ihope",
      artistName: "IHOPE",
    },
    {
      id: "ihope-215c",
      link: "https://bible-1328751369.cos.ap-guangzhou.myqcloud.com/music/215-信靠顺服.mp3",
      songTitle: "215-信靠顺服",
      songEnglishTitle: "",
      album: "ihope",
      artistName: "IHOPE",
    },
    {
      id: "ihope-215e",
      link: "https://bible-1328751369.cos.ap-guangzhou.myqcloud.com/music/215-信靠顺服-English.mp3",
      songTitle: "",
      songEnglishTitle: "215-信靠顺服-English",
      album: "ihope",
      artistName: "IHOPE",
    },
    {
      id: "ihope-219",
      link: "https://bible-1328751369.cos.ap-guangzhou.myqcloud.com/music/219-仰望那山.mp3",
      songTitle: "219-仰望那山",
      songEnglishTitle: "",
      album: "ihope",
      artistName: "IHOPE",
    },
    {
      id: "ihope-221",
      link: "https://bible-1328751369.cos.ap-guangzhou.myqcloud.com/music/221-我罪极重.mp3",
      songTitle: "221-我罪极重",
      songEnglishTitle: "",
      album: "ihope",
      artistName: "IHOPE",
    },
    {
      id: "ihope-225",
      link: "https://bible-1328751369.cos.ap-guangzhou.myqcloud.com/music/225-有一位神.mp3",
      songTitle: "225-有一位神",
      songEnglishTitle: "",
      album: "ihope",
      artistName: "IHOPE",
    },
    {
      id: "ihope-233",
      link: "https://bible-1328751369.cos.ap-guangzhou.myqcloud.com/music/233-喜传福音.mp3",
      songTitle: "233-喜传福音",
      songEnglishTitle: "",
      album: "ihope",
      artistName: "IHOPE",
    },
    {
      id: "ihope-237",
      link: "https://bible-1328751369.cos.ap-guangzhou.myqcloud.com/music/237-耶稣恩友.mp3",
      songTitle: "237-耶稣恩友",
      songEnglishTitle: "",
      album: "ihope",
      artistName: "IHOPE",
    },
    {
      id: "ihope-253",
      link: "https://bible-1328751369.cos.ap-guangzhou.myqcloud.com/music/253-万福源头.mp3",
      songTitle: "253-万福源头",
      songEnglishTitle: "",
      album: "ihope",
      artistName: "IHOPE",
    },
    {
      id: "ihope-259",
      link: "https://bible-1328751369.cos.ap-guangzhou.myqcloud.com/music/259-我以祷告来到你跟前.mp3",
      songTitle: "259-我以祷告来到你跟前",
      songEnglishTitle: "",
      album: "ihope",
      artistName: "IHOPE",
    },
    {
      id: "ihope-265",
      link: "https://bible-1328751369.cos.ap-guangzhou.myqcloud.com/music/265-欢声唱.mp3",
      songTitle: "265-欢声唱",
      songEnglishTitle: "",
      album: "ihope",
      artistName: "IHOPE",
    },
    {
      id: "ihope-269",
      link: "https://bible-1328751369.cos.ap-guangzhou.myqcloud.com/music/269-我要向高山举目.mp3",
      songTitle: "269-我要向高山举目",
      songEnglishTitle: "",
      album: "ihope",
      artistName: "IHOPE",
    },
    {
      id: "ihope-271",
      link: "https://bible-1328751369.cos.ap-guangzhou.myqcloud.com/music/271-美哉主耶稣.mp3",
      songTitle: "271-美哉主耶稣",
      songEnglishTitle: "",
      album: "ihope",
      artistName: "IHOPE",
    },
    {
      id: "ihope-275",
      link: "https://bible-1328751369.cos.ap-guangzhou.myqcloud.com/music/275-爱救了我.mp3",
      songTitle: "275-爱救了我",
      songEnglishTitle: "",
      album: "ihope",
      artistName: "IHOPE",
    },
    {
      id: "ihope-278",
      link: "https://bible-1328751369.cos.ap-guangzhou.myqcloud.com/music/278-为我异象.mp3",
      songTitle: "278-为我异象",
      songEnglishTitle: "",
      album: "ihope",
      artistName: "IHOPE",
    },
    {
      id: "ihope-279",
      link: "https://bible-1328751369.cos.ap-guangzhou.myqcloud.com/music/279-靠近十架.mp3",
      songTitle: "279-靠近十架",
      songEnglishTitle: "",
      album: "ihope",
      artistName: "IHOPE",
    },
    {
      id: "ihope-280",
      link: "https://bible-1328751369.cos.ap-guangzhou.myqcloud.com/music/280-求主同住.mp3",
      songTitle: "280-求主同住",
      songEnglishTitle: "",
      album: "ihope",
      artistName: "IHOPE",
    },
    {
      id: "ihope-284",
      link: "https://bible-1328751369.cos.ap-guangzhou.myqcloud.com/music/284-主耶和华是我牧者.mp3",
      songTitle: "284-主耶和华是我牧者",
      songEnglishTitle: "",
      album: "ihope",
      artistName: "IHOPE",
    },
    {
      id: "ihope-285",
      link: "https://bible-1328751369.cos.ap-guangzhou.myqcloud.com/music/285-使我做你和平差使.mp3",
      songTitle: "285-使我做你和平差使",
      songEnglishTitle: "",
      album: "ihope",
      artistName: "IHOPE",
    },
    {
      id: "ihope-286",
      link: "https://bible-1328751369.cos.ap-guangzhou.myqcloud.com/music/286 Victory in Jesus.mp3",
      songTitle: "",
      songEnglishTitle: "286-Victory in Jesus",
      album: "ihope",
      artistName: "IHOPE",
    },
    {
      id: "ihope-288",
      link: "https://bible-1328751369.cos.ap-guangzhou.myqcloud.com/music/288-充满我.mp3",
      songTitle: "288-充满我",
      songEnglishTitle: "",
      album: "ihope",
      artistName: "IHOPE",
    },
    {
      id: "ihope-289",
      link: "https://bible-1328751369.cos.ap-guangzhou.myqcloud.com/music/289- 古旧十架.mp3",
      songTitle: "289-古旧十架",
      songEnglishTitle: "",
      album: "ihope",
      artistName: "IHOPE",
    },
    {
      id: "ihope-291",
      link: "https://bible-1328751369.cos.ap-guangzhou.myqcloud.com/music/291-Anchor for the Soul.mp3",
      songTitle: "",
      songEnglishTitle: "291-Anchor for the Soul",
      album: "ihope",
      artistName: "IHOPE",
    },
    {
      id: "ihope-292",
      link: "https://bible-1328751369.cos.ap-guangzhou.myqcloud.com/music/292 Lead me to the Rock.mp3",
      songTitle: "",
      songEnglishTitle: "292-Lead me to the Rock",
      album: "ihope",
      artistName: "IHOPE",
    },
    {
      id: "ihope-293",
      link: "https://bible-1328751369.cos.ap-guangzhou.myqcloud.com/music/293-有人在为你祷告.mp3",
      songTitle: "293-有人在为你祷告",
      songEnglishTitle: "",
      album: "ihope",
      artistName: "IHOPE",
    },
    {
      id: "ihope-lamb",
      link: "https://bible-1328751369.cos.ap-guangzhou.myqcloud.com/music/主看顾小羊.mp3",
      songTitle: "主看顾小羊",
      songEnglishTitle: "",
      album: "ihope",
      artistName: "IHOPE",
    },
    {
      id: "ihope-joy",
      link: "https://bible-1328751369.cos.ap-guangzhou.myqcloud.com/music/Joy to the world.mp3",
      songTitle: "",
      songEnglishTitle: "Joy to the world",
      album: "ihope",
      artistName: "IHOPE",
    },
    {
      id: "ihope-come",
      link: "https://bible-1328751369.cos.ap-guangzhou.myqcloud.com/music/O Come, All Ye Faithfull.mp3",
      songTitle: "",
      songEnglishTitle: "O Come, All Ye Faithfull",
      album: "ihope",
      artistName: "IHOPE",
    },
    {
      id: "ihope-silent",
      link: "https://bible-1328751369.cos.ap-guangzhou.myqcloud.com/music/Silent Night.mp3",
      songTitle: "",
      songEnglishTitle: "Silent Night",
      album: "ihope",
      artistName: "IHOPE",
    },
    {
      id: "ihope-hark",
      link: "https://bible-1328751369.cos.ap-guangzhou.myqcloud.com/music/Hark! The Herald Angles Sing.mp3",
      songTitle: "",
      songEnglishTitle: "Hark! The Herald Angles Sing",
      album: "ihope",
      artistName: "IHOPE",
    },
  ],
};
